
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.1 EDK_P.15xf
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_XPS_GPIO_LEDS_DEVICE_ID,
		XPAR_XPS_GPIO_LEDS_BASEADDR,
		XPAR_XPS_GPIO_LEDS_INTERRUPT_PRESENT,
		XPAR_XPS_GPIO_LEDS_IS_DUAL
	},
	{
		XPAR_XPS_GPIO_SWITCHES_DEVICE_ID,
		XPAR_XPS_GPIO_SWITCHES_BASEADDR,
		XPAR_XPS_GPIO_SWITCHES_INTERRUPT_PRESENT,
		XPAR_XPS_GPIO_SWITCHES_IS_DUAL
	}
};


